- name: install mysql repository
  yum:
    state: present
    name: http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
    validate_certs: yes
        
- name: Remove MariaDB
  yum: name=mariadb-libs state=absent
  ignore_errors: yes

- name: MySQL5.7 client install
  yum: name=mysql-community-client state=present

- name: MySQL5.7 server install
  yum: name=mysql-community-server state=present

- name: mkdir -p /export/mysql/mysql
  shell: mkdir -p /export/mysql/mysql/tmp ; mkdir -p /export/mysql/mysql1/tmp ; chown -R mysql.mysql /export/mysql

- name: config
  copy: src=../files/my.cnf dest=/etc/my.cnf backup=yes

- name: create slowlog
  shell: touch /var/log/mysqld.slow.log ; chown mysql /var/log/mysqld.slow.log ; touch /var/log/mysqld1.slow.log ; chown mysql /var/log/mysqld1.slow.log

- name: mysql_install_db 
  shell: mysqld --initialize --datadir=/export/mysql/mysql --user=mysql --ignore-db-dir=tmp; mysqld --initialize --datadir=/export/mysql/mysql1 --user=mysql --ignore-db-dir=tmp
  ignore_errors: yes

- name: mysql start
  service: name=mysqld state=restarted
  
- name: mysql enabled
  service: name=mysqld enabled=yes
